-- Task 3: a separate "warehouse" schema that holds the star schema (built from the OLTP tables)
CREATE SCHEMA IF NOT EXISTS warehouse;

-- dimension: one row per customer, SCD Type 1 (we overwrite it on every reload)
CREATE TABLE IF NOT EXISTS warehouse.dim_customers (
    customer_key INT PRIMARY KEY,
    customer_id  INT NOT NULL UNIQUE,
    full_name    VARCHAR(100) NOT NULL,
    email        VARCHAR(100) NOT NULL,
    city         VARCHAR(50)  NOT NULL,
    signup_date  DATE
);

-- dimension: one row per product
CREATE TABLE IF NOT EXISTS warehouse.dim_products (
    product_key INT PRIMARY KEY,
    product_id  INT NOT NULL UNIQUE,
    title       VARCHAR(150)  NOT NULL,
    category    VARCHAR(50)   NOT NULL,
    price       NUMERIC(10,2) NOT NULL
);

-- dimension: one row per calendar day, keyed by a YYYYMMDD number
CREATE TABLE IF NOT EXISTS warehouse.dim_date (
    date_key    INT PRIMARY KEY,
    full_date   DATE NOT NULL UNIQUE,
    year        SMALLINT NOT NULL,
    quarter     SMALLINT NOT NULL,
    month       SMALLINT NOT NULL,
    month_name  VARCHAR(9) NOT NULL,
    day         SMALLINT NOT NULL,
    day_of_week SMALLINT NOT NULL,
    day_name    VARCHAR(9) NOT NULL,
    is_weekend  BOOLEAN NOT NULL
);

-- reports filter by a date range far more often than by the key, so full_date needs its own index
CREATE INDEX IF NOT EXISTS idx_dim_date_full_date ON warehouse.dim_date (full_date);

-- fact: one row per order, pointing at the three dimensions with their surrogate keys
CREATE TABLE IF NOT EXISTS warehouse.fact_orders (
    order_key    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     INT NOT NULL UNIQUE,
    customer_key INT NOT NULL REFERENCES warehouse.dim_customers(customer_key),
    product_key  INT NOT NULL REFERENCES warehouse.dim_products(product_key),
    date_key     INT NOT NULL REFERENCES warehouse.dim_date(date_key),
    quantity     INT NOT NULL,
    unit_price   NUMERIC(10,2) NOT NULL,
    total_amount NUMERIC(12,2) NOT NULL,
    status       VARCHAR(20) NOT NULL
);

-- same four statuses the OLTP side allows. Drop-then-add so an older warehouse picks the rule up too
ALTER TABLE warehouse.fact_orders DROP CONSTRAINT IF EXISTS fact_orders_status_check;
ALTER TABLE warehouse.fact_orders ADD CONSTRAINT fact_orders_status_check
    CHECK (status IN ('completed', 'pending', 'returned', 'cancelled'));
